name: bnf
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - nextflow
  - bwa
  - samtools=1.17
  - bcftools=1.17
  - fastqc
  - cutadapt
  - sratoolkit
  - openjdk 
